---
  - hosts: spine,leaf,jinja2_leaf,jinja2_spine
    connection: local
    vars:
      ios_provider:
        transport: nxapi
        username: "{{ user }}"
        password: "{{ pwd }}"
        host: "{{ inventory_hostname }}"
    tasks:
      - name: save running
        nxos_config:
           provider: "{{ ios_provider }}"
           backup: yes
           timeout: 20

